// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqAbl2a7dwvua_F5x9XmzwRHELNSHuMLo',
    appId: '1:837646090587:web:a0ea10eeca0b9f6fdcda7e',
    messagingSenderId: '837646090587',
    projectId: 'shadify-the-wedding-planner',
    authDomain: 'shadify-the-wedding-planner.firebaseapp.com',
    storageBucket: 'shadify-the-wedding-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3czLuTXMPQiOtifpxPSDj_bxKAvO8-oQ',
    appId: '1:837646090587:android:df90f2fc219e119cdcda7e',
    messagingSenderId: '837646090587',
    projectId: 'shadify-the-wedding-planner',
    storageBucket: 'shadify-the-wedding-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALv4V1b31LA87W4fbs2HEhiV9OXmH_-dg',
    appId: '1:837646090587:ios:5bca975f0bd04241dcda7e',
    messagingSenderId: '837646090587',
    projectId: 'shadify-the-wedding-planner',
    storageBucket: 'shadify-the-wedding-planner.firebasestorage.app',
    iosBundleId: 'com.example.weddingPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALv4V1b31LA87W4fbs2HEhiV9OXmH_-dg',
    appId: '1:837646090587:ios:5bca975f0bd04241dcda7e',
    messagingSenderId: '837646090587',
    projectId: 'shadify-the-wedding-planner',
    storageBucket: 'shadify-the-wedding-planner.firebasestorage.app',
    iosBundleId: 'com.example.weddingPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqAbl2a7dwvua_F5x9XmzwRHELNSHuMLo',
    appId: '1:837646090587:web:362afd5b82f85475dcda7e',
    messagingSenderId: '837646090587',
    projectId: 'shadify-the-wedding-planner',
    authDomain: 'shadify-the-wedding-planner.firebaseapp.com',
    storageBucket: 'shadify-the-wedding-planner.firebasestorage.app',
  );

}